# Generated by Django 5.1.2 on 2024-10-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.IntegerField(default=9999999)),
                ('stock', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
