# Generated by Django 5.1.2 on 2024-10-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('HOGAR', 'Hogar'), ('COCINA', 'Cocina'), ('JARDIN', 'Jardín'), ('SIN_CATEGORIA', 'Sin categoría')], default='SIN_CATEGORIA', max_length=50),
        ),
    ]
