# Generated by Django 5.1.2 on 2024-10-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('productos_vip', 'Puede visualizar exclusivos'),)},
        ),
    ]
